# Generated by Django 5.2.16 on 2026-08-04 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('part_of_speech', models.CharField(max_length=32)),
                ('definition', models.CharField(max_length=512)),
                ('is_phrase', models.BooleanField(default=False)),
                ('word_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='wordbank.wordbank')),
            ],
            options={
                'unique_together': {('word_bank', 'word')},
            },
        ),
    ]
