# Generated by Django 5.2.16 on 2026-08-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='pronounce',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(max_length=64),
        ),
    ]
