# Generated by Django 5.2.16 on 2026-08-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbank', '0003_shared_words_refactor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordbankentry',
            options={'verbose_name_plural': 'Word bank entries'},
        ),
        migrations.AddField(
            model_name='word',
            name='antonyms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='word',
            name='english_definition',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='word',
            name='examples',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='word',
            name='synonyms',
            field=models.TextField(blank=True, default=''),
        ),
    ]
