# Generated by Django 5.2.16 on 2026-08-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbank', '0004_enrich_word_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='pronounce_uk',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='word',
            name='pronounce_us',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
