# Generated by Django 5.2.16 on 2026-08-08 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordbank', '0005_add_us_uk_pronounce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='pronounce',
        ),
    ]
