# Generated by Django 5.2.16 on 2026-08-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected_word_bank_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
