# Generated by Django 5.2.16 on 2026-08-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_selected_word_bank_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='article_length',
            field=models.IntegerField(default=500),
        ),
    ]
