# Generated by Django 5.2.16 on 2026-08-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loginrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_limit',
            field=models.IntegerField(default=-1),
        ),
    ]
