# Generated by Django 5.2.16 on 2026-08-08 05:57

from django.db import migrations, models


def reset_old_default_length(apps, schema_editor):
    """Profiles still at the old default (500) get the new default (350).
    Deliberately customized values (e.g. 300) are left untouched."""
    Profile = apps.get_model("accounts", "Profile")
    Profile.objects.filter(article_length=500).update(article_length=350)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_daily_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='article_length',
            field=models.IntegerField(default=350),
        ),
        migrations.RunPython(reset_old_default_length, migrations.RunPython.noop),
    ]
