# Generated by Django 5.2.16 on 2026-08-06 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        ('wordbank', '0003_shared_words_refactor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['user', '-generated_at'], name='article_user_gen_idx'),
        ),
    ]
