# Generated by Django 5.2.16 on 2026-08-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_article_article_user_gen_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwordstatus',
            name='last_reviewed_at',
        ),
        migrations.RemoveField(
            model_name='userwordstatus',
            name='next_review_at',
        ),
        migrations.RemoveField(
            model_name='userwordstatus',
            name='review_interval',
        ),
        migrations.AddField(
            model_name='userwordstatus',
            name='mastered_count',
            field=models.IntegerField(default=0),
        ),
    ]
