# Generated by Django 5.2.16 on 2026-08-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_simplify_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='userwordstatus',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('review', 'Review'), ('mastered', 'Mastered')], default='new', max_length=16),
        ),
    ]
